/**
 * @license
 * lodash 3.10.1 (Custom Build) lodash.com/license | Underscore.js 1.8.3 underscorejs.org/LICENSE
 * Build: `lodash include="debounce,throttle,delay,isPlainObject,isArray,isFunction,clone,cloneDeep"`
 */
;(function(){function t(t){return!!t&&typeof t=="object"}function n(){}function r(t,n){var r=-1,e=t.length;for(n||(n=Array(e));++r<e;)n[r]=t[r];return n}function e(t,n){for(var r=-1,e=t.length;++r<e&&false!==n(t[r],r,t););return t}function o(t,n){var r;if(null==n)r=t;else{r=It(n);var e=t;e||(e={});for(var o=-1,c=r.length;++o<c;){var u=r[o];e[u]=n[u]}r=e}return r}function c(t,n,u,a,f,l,s){var g;if(u&&(g=f?u(t,a,f):u(t)),g!==I)return g;if(!x(t))return t;if(a=Tt(t)){if(g=p(t),!n)return r(t,g)}else{var h=st.call(t),v=h==C;
if(h!=D&&h!=U&&(!v||f))return Z[h]?b(t,h,n):f?t:{};if(ct(t))return f?t:{};if(g=y(v?{}:t),!n)return o(g,t)}for(l||(l=[]),s||(s=[]),f=l.length;f--;)if(l[f]==t)return s[f];return l.push(t),s.push(g),(a?e:i)(t,function(r,e){g[e]=c(r,n,u,e,t,l,s)}),g}function u(t,n,r){if(typeof t!="function")throw new TypeError(P);return setTimeout(function(){t.apply(I,r)},n)}function a(t,n){Ot(t,n,S)}function i(t,n){return Ot(t,n,It)}function f(t,n){return typeof t!="function"?T:n===I?t:function(r,e,o){return t.call(n,r,e,o);
}}function l(t){var n=new yt(t.byteLength);return new ht(n).set(new ht(t)),n}function s(t,n){var r=null==t?I:t[n];return O(r)?r:I}function p(t){var n=t.length,r=new t.constructor(n);return n&&"string"==typeof t[0]&&lt.call(t,"index")&&(r.index=t.index,r.input=t.input),r}function y(t){return t=t.constructor,typeof t=="function"&&t instanceof t||(t=Object),new t}function b(t,n,r){var e=t.constructor;switch(n){case B:return l(t);case F:case $:return new e(+t);case M:case N:case R:case V:case q:case z:
case G:case H:case J:return e instanceof e&&(e=dt[n]),n=t.buffer,new e(r?l(n):n,t.byteOffset,t.length);case L:case _:return new e(t);case W:var o=new e(t.source,K.exec(t));o.lastIndex=t.lastIndex}return o}function g(t,n){return t=typeof t=="number"||X.test(t)?+t:-1,n=null==n?wt:n,-1<t&&0==t%1&&t<n}function h(t){return typeof t=="number"&&-1<t&&0==t%1&&t<=wt}function v(t){for(var n=S(t),r=n.length,e=r&&t.length,o=!!e&&h(e)&&(Tt(t)||d(t)||E(t)),c=-1,u=[];++c<r;){var a=n[c];(o&&g(a,e)||lt.call(t,a))&&u.push(a);
}return u}function j(t){if(n.support.unindexedChars&&E(t)){for(var r=-1,e=t.length,o=Object(t);++r<e;)o[r]=t.charAt(r);return o}return x(t)?t:Object(t)}function m(t,n,r){function e(n,r){r&&clearTimeout(r),i=p=y=I,n&&(b=St(),f=t.apply(s,a),p||i||(a=s=I))}function o(){var t=n-(St()-l);0>=t||t>n?e(y,i):p=setTimeout(o,t)}function c(){e(h,p)}function u(){if(a=arguments,l=St(),s=this,y=h&&(p||!v),false===g)var r=v&&!p;else{i||v||(b=l);var e=g-(l-b),u=0>=e||e>g;u?(i&&(i=clearTimeout(i)),b=l,f=t.apply(s,a)):i||(i=setTimeout(c,e));
}return u&&p?p=clearTimeout(p):p||n===g||(p=setTimeout(o,n)),r&&(u=true,f=t.apply(s,a)),!u||p||i||(a=s=I),f}var a,i,f,l,s,p,y,b=0,g=false,h=true;if(typeof t!="function")throw new TypeError(P);if(n=0>n?0:+n||0,true===r)var v=true,h=false;else x(r)&&(v=!!r.leading,g="maxWait"in r&&jt(+r.maxWait||0,n),h="trailing"in r?!!r.trailing:h);return u.cancel=function(){p&&clearTimeout(p),i&&clearTimeout(i),b=0,i=p=y=I},u}function w(t,n){if(typeof t!="function")throw new TypeError(P);return n=jt(n===I?t.length-1:+n||0,0),function(){
for(var r=arguments,e=-1,o=jt(r.length-n,0),c=Array(o);++e<o;)c[e]=r[n+e];switch(n){case 0:return t.call(this,c);case 1:return t.call(this,r[0],c);case 2:return t.call(this,r[0],r[1],c)}for(o=Array(n+1),e=-1;++e<n;)o[e]=r[e];return o[n]=c,t.apply(this,o)}}function d(n){return t(n)&&null!=n&&h(Et(n))&&lt.call(n,"callee")&&!bt.call(n,"callee")}function A(t){return x(t)&&st.call(t)==C}function x(t){var n=typeof t;return!!t&&("object"==n||"function"==n)}function O(n){return null==n?false:A(n)?pt.test(ft.call(n)):t(n)&&(ct(n)?pt:Q).test(n);
}function E(n){return typeof n=="string"||t(n)&&st.call(n)==_}function S(t){if(null==t)return[];x(t)||(t=Object(t));for(var r=t.length,e=n.support,r=r&&h(r)&&(Tt(t)||d(t)||E(t))&&r||0,o=t.constructor,c=-1,o=A(o)&&o.prototype||at,u=o===t,a=Array(r),i=0<r,f=e.enumErrorProps&&(t===ut||t instanceof Error),l=e.enumPrototypes&&A(t);++c<r;)a[c]=c+"";for(var s in t)l&&"prototype"==s||f&&("message"==s||"name"==s)||i&&g(s,r)||"constructor"==s&&(u||!lt.call(t,s))||a.push(s);if(e.nonEnumShadows&&t!==at)for(r=t===it?_:t===ut?k:st.call(t),
e=At[r]||At[D],r==D&&(o=at),r=Y.length;r--;)s=Y[r],c=e[s],u&&c||(c?!lt.call(t,s):t[s]===o[s])||a.push(s);return a}function T(t){return t}var I,P="Expected a function",U="[object Arguments]",F="[object Boolean]",$="[object Date]",k="[object Error]",C="[object Function]",L="[object Number]",D="[object Object]",W="[object RegExp]",_="[object String]",B="[object ArrayBuffer]",M="[object Float32Array]",N="[object Float64Array]",R="[object Int8Array]",V="[object Int16Array]",q="[object Int32Array]",z="[object Uint8Array]",G="[object Uint8ClampedArray]",H="[object Uint16Array]",J="[object Uint32Array]",K=/\w*$/,Q=/^\[object .+?Constructor\]$/,X=/^\d+$/,Y="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Z={};
Z[U]=Z["[object Array]"]=Z[B]=Z[F]=Z[$]=Z[M]=Z[N]=Z[R]=Z[V]=Z[q]=Z[L]=Z[D]=Z[W]=Z[_]=Z[z]=Z[G]=Z[H]=Z[J]=true,Z[k]=Z[C]=Z["[object Map]"]=Z["[object Set]"]=Z["[object WeakMap]"]=false;var tt={"function":true,object:true},nt=tt[typeof exports]&&exports&&!exports.nodeType&&exports,rt=tt[typeof module]&&module&&!module.nodeType&&module,et=tt[typeof self]&&self&&self.Object&&self,ot=tt[typeof window]&&window&&window.Object&&window,tt=rt&&rt.exports===nt&&nt,et=nt&&rt&&typeof global=="object"&&global&&global.Object&&global||ot!==(this&&this.window)&&ot||et||this,ct=function(){
try{Object({toString:0}+"")}catch(t){return function(){return false}}return function(t){return typeof t.toString!="function"&&typeof(t+"")=="string"}}(),ot=Array.prototype,ut=Error.prototype,at=Object.prototype,it=String.prototype,ft=Function.prototype.toString,lt=at.hasOwnProperty,st=at.toString,pt=RegExp("^"+ft.call(lt).replace(/[\\^$.*+?()[\]{}|]/g,"\\$&").replace(/hasOwnProperty|(function).*?(?=\\\()| for .+?(?=\\\])/g,"$1.*?")+"$"),yt=et.ArrayBuffer,bt=at.propertyIsEnumerable,gt=ot.splice,ht=et.Uint8Array,ot=s(Array,"isArray"),vt=s(Object,"keys"),jt=Math.max,mt=s(Date,"now"),wt=9007199254740991,dt={};
dt[M]=et.Float32Array,dt[N]=et.Float64Array,dt[R]=et.Int8Array,dt[V]=et.Int16Array,dt[q]=et.Int32Array,dt[z]=ht,dt[G]=et.Uint8ClampedArray,dt[H]=et.Uint16Array,dt[J]=et.Uint32Array;var At={};At["[object Array]"]=At[$]=At[L]={constructor:true,toLocaleString:true,toString:true,valueOf:true},At[F]=At[_]={constructor:true,toString:true,valueOf:true},At[k]=At[C]=At[W]={constructor:true,toString:true},At[D]={constructor:true},e(Y,function(t){for(var n in At)if(lt.call(At,n)){var r=At[n];r[t]=lt.call(r,t)}});var xt=n.support={};
!function(t){function n(){this.x=t}var r={0:t,length:t},e=[];n.prototype={valueOf:t,y:t};for(var o in new n)e.push(o);xt.enumErrorProps=bt.call(ut,"message")||bt.call(ut,"name"),xt.enumPrototypes=bt.call(n,"prototype"),xt.nonEnumShadows=!/valueOf/.test(e),xt.ownLast="x"!=e[0],xt.spliceObjects=(gt.call(r,0,1),!r[0]),xt.unindexedChars="xx"!="x"[0]+Object("x")[0]}(1,0);var Ot=function(t){return function(n,r,e){var o=j(n);e=e(n);for(var c=e.length,u=t?c:-1;t?u--:++u<c;){var a=e[u];if(false===r(o[a],a,o))break;
}return n}}(),Et=function(t){return function(n){return null==n?I:j(n)[t]}}("length"),St=mt||function(){return(new Date).getTime()},mt=w(function(t,n,r){return u(t,n,r)}),Tt=ot||function(n){return t(n)&&h(n.length)&&"[object Array]"==st.call(n)},It=vt?function(t){var r=null==t?I:t.constructor;return typeof r=="function"&&r.prototype===t||(typeof t=="function"?n.support.enumPrototypes:null!=t&&h(Et(t)))?v(t):x(t)?vt(t):[]}:v;n.debounce=m,n.delay=mt,n.keys=It,n.keysIn=S,n.restParam=w,n.throttle=function(t,n,r){
var e=true,o=true;if(typeof t!="function")throw new TypeError(P);return false===r?e=false:x(r)&&(e="leading"in r?!!r.leading:e,o="trailing"in r?!!r.trailing:o),m(t,n,{leading:e,maxWait:+n,trailing:o})},n.clone=function(t,n,r,e){var o;if((o=n)&&(o=typeof n!="boolean")){o=n;var u=r;if(x(u)){var a=typeof o;("number"==a?null!=u&&h(Et(u))&&g(o,u.length):"string"==a&&o in u)?(o=u[o],o=t===t?t===o:o!==o):o=false}else o=false}return o?n=false:typeof n=="function"&&(e=r,r=n,n=false),typeof r=="function"?c(t,n,f(r,e)):c(t,n)},n.cloneDeep=function(t,n,r){
return typeof n=="function"?c(t,true,f(n,r)):c(t,true)},n.identity=T,n.isArguments=d,n.isArray=Tt,n.isFunction=A,n.isNative=O,n.isObject=x,n.isPlainObject=function(r){var e;if(!t(r)||st.call(r)!=D||ct(r)||d(r)||!(lt.call(r,"constructor")||(e=r.constructor,typeof e!="function"||e instanceof e)))return false;var o;return n.support.ownLast?(a(r,function(t,n,r){return o=lt.call(r,n),false}),false!==o):(a(r,function(t,n){o=n}),o===I||lt.call(r,o))},n.isString=E,n.now=St,n.VERSION="3.10.1",typeof define=="function"&&typeof define.amd=="object"&&define.amd?(et._=n,
define(function(){return n})):nt&&rt?tt?(rt.exports=n)._=n:nt._=n:et._=n}).call(this);